# VARIABLE VALUES
@baseUrl = 'http://localhost:3000/api/v1'
@id = 1

### Create a Post
POST {{baseUrl}}/posts HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "author": "Maboku Seimela",
    "content": "I am going to do better in my relationships",
    "is_private": false
}

### Get all Posts
GET {{baseUrl}}/posts HTTP/1.1
Accept: application/json

### Uppdate a post
PUT {{baseUrl}}/posts/{{id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "author": "Seimela Maboku",
    "content": "I am going to be a better version of myself for my family",
    "is_private": true
}